### ISSUE TITLE
JWT validation error

### ISSUE THREAD

**Issue by davidrneves** [xmidt-org/webpa-common#223]
I'm trying to make a simple scytale API call: curl -H "Authorization: Bearer <token>" -X GET 'http://host:port/api/v2/device/mac:0001A2B112233/stat' but always get the following response:

{"message": "request denied"}

Could you please provide with a detailed explanation on how to generate a valid JWT token with the provided Comcast KeyServer?

Thanks in advance.

**Comment by schmidtw** [comment]
David,

We're working on a "good suggestion" as we use an internal service for this.  Will respond shortly.

Best,
Wes

**Comment by kristinaspring** [comment]
hi David and Wes,

Is this still an issue? Can we close this?
