### ISSUE TITLE
Deprecate authStatus Message

### ISSUE THREAD

**Issue by kcajmagic** [xmidt-org/webpa-common#324]
Currently the authStatus Message is not used by [parodus](https://github.com/Comcast/parodus) and removing this message will free up the resources used by the go routines.

For this to be complete the following needs to happen:
- [x] delete `authStatus` code from XMiDT
- [ ] update docs to show the message is now deprecated
- [x] update [kratos](https://github.com/Comcast/kratos) to not use the `authStatus` Message
- [x] Revert PR #322 and Close PR #294

**Comment by kcajmagic** [comment]
kratos currently does not use the Authorization Status Message. Marking it as done.

**Comment by kcajmagic** [comment]
Submitted PR #325 to deprecate `AuthorizationStatusMessage`

**Comment by kristinaspring** [comment]
@kcajmagic does more need to be done here?

**Comment by kcajmagic** [comment]
Work on this has been completed.
