### ISSUE TITLE
SNS Unsubscribe doesn't check Subscription ID (ARN)

### ISSUE THREAD

**Issue by ajgale** [xmidt-org/webpa-common#362]
When unsubscribing from old SNS subscriptions, the SubscriptionID (topicARN) is not being checked for invalid values, such as "Deleted" or "PendingConfirmation"

**Comment by joe94** [comment]
Minor but still valid defect. It'll serve to avoid unsubscribing from subscriptions in the "pending confirmation" state. SNS doesn't allow unsubscribing/deleting these as they are pruned after 3 days of age.

**Comment by joe94** [comment]
We're abandoning SNS in favor or Argus (https://github.com/xmidt-org/argus) for storing webhook subscriptions.
