### ISSUE TITLE
metrics should expose version of the server

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/webpa-common#367]
Each server should expose it's version via prometheus metrics.  Here's an example:
`#HELP node_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which node_exporter was built.
node_exporter_build_info{branch="HEAD",goversion="go1.9.2",revision="ba5da2c29ae7f6209a88cb58676ba5ba029ad785",version="0.15.1"} 1`

**Comment by kristinaspring** [comment]
I believe this is done.
