### ISSUE TITLE
Bump go-kit to v0.9.0

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/webpa-common#421]
https://github.com/xmidt-org/webpa-common/blob/7965ed4246c174d64f6cbd8051bceceda9836485/glide.yaml#L12

**Comment by kristinaspring** [comment]
since we upgraded to mods, this can now be found here:
https://github.com/xmidt-org/webpa-common/blob/master/go.mod#L17

**Comment by kristinaspring** [comment]
https://github.com/xmidt-org/webpa-common/blob/master/go.mod#L16

```	github.com/go-kit/kit v0.8.0
```

**Comment by joe94** [comment]
Check if there's a newer version and ensure all dependencies work.

**Comment by joe94** [comment]
Looks like this has been fixed 🎉  https://github.com/xmidt-org/webpa-common/blob/5150386d727c4b6dad78981a89a1afab909cef02/go.mod#L11
