### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by joe94** [xmidt-org/webpa-common#425]
The main README provides a basic development setup with tools such as glide that we have abandoned.

**Comment by kristinaspring** [comment]
To do:
- [ ] Remove mentions of glide
- [ ] Update go version to be at least 1.12
- [ ] Updated any `github.com/Comcast` links to `github.com/xmidt-org`
- [ ] Change `./test.sh` command to instead run go test with coverage and race flags
