### ISSUE TITLE
Use the service name for sd metrics labels

### ISSUE THREAD

**Issue by johnabass** [xmidt-org/webpa-common#473]
Currently, there is an autogenerated key used for multiple go-kit `Instancer` objects.  This key uses not only the service name, but also the tags and other aspects of the configured watch.  This is done to guarantee uniqueness when multiple watches are configured that use the same service, tags, etc.

This autogenerated key is being used as the label for the various `sd` metrics.  Instead, we should use the service name of the watch, e.g. `talaria` or `caduceus`.

https://github.com/xmidt-org/webpa-common/blob/master/service/instancers.go#L32
https://github.com/xmidt-org/webpa-common/blob/master/service/monitor/listener.go#L69

**Comment by joe94** [comment]
@johnabass, one solution I can think of for this is exporting https://github.com/xmidt-org/webpa-common/blob/master/service/instancers.go#L7

to fetch the service name from the contextual Metadata

**Comment by johnabass** [comment]
The best would would be to augment the `Event` object with the service.  Then the listeners can directly reference the service name.
