### ISSUE TITLE
Start Function in New Goroutine

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/webpa-common#476]
https://github.com/xmidt-org/webpa-common/blob/a81c75dd06641b1a9928dcb93f60faeba4eebc3d/webhook/start.go#L177

It seems the intention of this was to have a timeout for the request.  I don't think the timeout is working correctly since everything is being done in a single thread.  If `fn` starts in a new goroutine, then we can timeout instead of waiting for the http request to complete.

It seems like with very little extra work, we could also get rid of this timeout logic and add a timeout to the http.Client
https://godoc.org/net/http#Client

**Comment by kristinaspring** [comment]
@schmidtw, @johnabass, your insights on this would be great.

**Comment by johnabass** [comment]
Using `context` objects to timeout `http.Client` requests is probably best.  This probably will become necessary when `argus` launches.

**Comment by joe94** [comment]
This should no longer be relevant after switching to argus!

**Comment by joe94** [comment]
Closing this as we're moving forward with Argus.
