### ISSUE TITLE
What happens when we fail to confirm a subscription?

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/webpa-common#477]
https://github.com/xmidt-org/webpa-common/blob/a81c75dd06641b1a9928dcb93f60faeba4eebc3d/webhook/aws/sns_handler.go#L201

After subscribing to SNS, SNS sends back a subscription confirmation.  However, sometimes we get an error when trying to confirm the subscription.  Will we still be subscribed? As far as I can tell, Subscribe() runs on startup and if it succeeds, it never runs again.

**Comment by joe94** [comment]
When confirmation fails for a subscription, the webhook component doesn't get any updates. This will no longer be relevant once the webhook library moves away from SNS.

**Comment by joe94** [comment]
Reopened by mistake. This is no longer relevant per the plans to switch to Argus.
