### ISSUE TITLE
Don't try to unsubscribe

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/webpa-common#478]
when a caduceus confirms its subscription, it tries to unsubscribe old subscriptions that might belong to it (I think that's what it's doing), so it calls ListSubscriptionByTopic :
https://github.com/xmidt-org/webpa-common/blob/a81c75dd06641b1a9928dcb93f60faeba4eebc3d/webhook/aws/sns_handler.go#L396

We don't need this block of code. A start up sequence should simply attempt to subscribe. If the subscription results in an error because a subscription already exists, just ignore the error and move on.

**Comment by joe94** [comment]
If we decide to work on this before we move away from SNS for webhooks:
We need to come up with a tool to move this logic to as it doesn't belong here. This component is intended as a way to perform old subscriptions cleanup at system exit.

**Comment by joe94** [comment]
We should reopen this if necessary but with the switch to Argus, this won't be relevant.
