### ISSUE TITLE
Rehasher needs to filter by service key and/or tags

### ISSUE THREAD

**Issue by johnabass** [xmidt-org/webpa-common#481]
The `device/rehasher` package needs to be configured with and take into account the particular service it's listening to.

https://github.com/xmidt-org/webpa-common/blob/bf7f42408d7b0ccce0146a8b1e00382c4bcc4c64/device/rehasher/rehasher.go#L131

**Comment by ilawjr** [comment]
To test:
1) connect device to talaria
2) shutdown caduceus
3) verify device is not disconnected/reshashed.
