### ISSUE TITLE
pprof has no default address

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/webpa-common#516]
https://github.com/xmidt-org/webpa-common/blob/bad564775783f1af8ae9373f29f157db733bc428/server/viper.go#L164

What happens when pprof address isn't set correctly? Currently, it looks like it's defaulting to port 80.

**Comment by joe94** [comment]
Port 80 must be the golang server default port. 

I think it'd be sensible to either use `6060` (from the pprof docs - https://golang.org/pkg/net/http/pprof/) or `9999` as the default value.

**Comment by kristinaspring** [comment]
I think `6060` sounds like a good plan.
